<?xml version="1.0" encoding="utf-8"?><Database Name="evesharp" Class="evesharpDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=\\.\pipe\MSSQL$MSSQLEXPRESS\sql\query;Initial Catalog=evesharp;Integrated Security=True;Pooling=False" SettingsObjectName="EVESharp.ClusterControler.Properties.Settings" SettingsPropertyName="evesharpConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.character_" Member="character_s">
    <Type Name="character_">
      <Column Name="characterID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="accountID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(85) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="bounty" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="balance" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="securityRating" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="petitionMessage" Type="System.String" DbType="NVarChar(85) NOT NULL" CanBeNull="false" />
      <Column Name="logonMinutes" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="corporationID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="corpRole" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="rolesAtAll" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="rolesAtBase" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="rolesAtHQ" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="rolesAtOther" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="corporationDateTime" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="startDateTime" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="createDateTime" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ancestryID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="careerID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="schoolID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="careerSpecialityID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="accessoryID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="beardID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="costumeID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="decoID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="eyebrowsID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="eyesID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="hairID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="lipstickID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="makeupID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="skinID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="backgroundID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="lightID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="headRotation1" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="headRotation2" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="headRotation3" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="eyeRotation1" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="eyeRotation2" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="eyeRotation3" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="camPos1" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="camPos2" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="camPos3" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="morph1e" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="morph1n" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="morph1s" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="morph1w" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="morph2e" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="morph2n" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="morph2s" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="morph2w" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="morph3e" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="morph3n" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="morph3s" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="morph3w" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="morph4e" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="morph4n" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="morph4s" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="morph4w" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="stationID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="solarSystemID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="constellationID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="regionID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="online" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Association Name="entity_character_" Member="entity" ThisKey="characterID" OtherKey="itemID" Type="entity" IsForeignKey="true" />
      <Association Name="account_character_" Member="account" ThisKey="accountID" OtherKey="accountID" Type="account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.cacheinfo" Member="cacheinfos">
    <Type Name="cacheinfo">
      <Column Name="cacheName" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cacheData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="cacheTime" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="nodeID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="version" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.invtypes" Member="invtypes">
    <Type Name="invtype">
      <Column Name="typeID" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="groupID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="typeName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(3000)" CanBeNull="true" />
      <Column Name="graphicID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="radius" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="mass" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="volume" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="capacity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="portionSize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="raceID" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="basePrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="published" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="marketGroupID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="chanceOfDuplicating" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="invtype_entity" Member="entities" ThisKey="typeID" OtherKey="typeID" Type="entity" />
    </Type>
  </Table>
  <Table Name="dbo.entity" Member="entities">
    <Type Name="entity">
      <Column Name="itemID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="itemName" Type="System.String" DbType="NVarChar(85) NOT NULL" CanBeNull="false" />
      <Column Name="typeID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ownerID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="locationID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="flag" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="contraband" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="singleton" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="x" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="y" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="z" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="customInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Member="nodeID" Type="System.Int16" CanBeNull="false" />
      <Association Name="entity_character_" Member="character_s" ThisKey="itemID" OtherKey="characterID" Type="character_" />
      <Association Name="entity_solarsystemsloaded" Member="solarsystemsloadeds" ThisKey="itemID" OtherKey="solarSystemID" Type="solarsystemsloaded" />
      <Association Name="invtype_entity" Member="invtype" ThisKey="typeID" OtherKey="typeID" Type="invtype" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.solarsystemsloaded" Member="solarsystemsloadeds">
    <Type Name="solarsystemsloaded">
      <Column Name="solarSystemID" Type="System.Int64" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nodeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="entity_solarsystemsloaded" Member="entity" ThisKey="solarSystemID" OtherKey="itemID" Type="entity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.account" Member="accounts">
    <Type Name="account">
      <Column Name="accountID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="accountName" Type="System.String" DbType="NVarChar(48) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="role" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="online" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="banned" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="account_character_" Member="character_s" ThisKey="accountID" OtherKey="accountID" Type="character_" />
    </Type>
  </Table>
</Database>