namespace EVESharp.Node.Inventory.Items.Types.Information;

public class Character
{
    public int     AccountID             { get; init; }
    public int?    ActiveCloneID         { get; set; }
    public string  Title                 { get; init; }
    public string  Description           { get; set; }
    public double  SecurityRating        { get; init; }
    public string  PetitionMessage       { get; init; }
    public int     LogonMinutes          { get; init; }
    public int     CorporationID         { get; set; }
    public int?    AllianceID            { get; set; }
    public long    Roles                 { get; set; }
    public long    RolesAtBase           { get; set; }
    public long    RolesAtHq             { get; set; }
    public long    RolesAtOther          { get; set; }
    public long    CorporationDateTime   { get; set; }
    public long    StartDateTime         { get; init; }
    public long    CreateDateTime        { get; init; }
    public int     AncestryID            { get; init; }
    public int     CareerID              { get; init; }
    public int     SchoolID              { get; init; }
    public int     CareerSpecialityID    { get; init; }
    public int     Gender                { get; init; }
    public int?    AccessoryID           { get; set; }
    public int?    BeardID               { get; init; }
    public int     CostumeID             { get; init; }
    public int?    DecoID                { get; init; }
    public int     EyebrowsID            { get; init; }
    public int     EyesID                { get; init; }
    public int     HairID                { get; init; }
    public int?    LipstickID            { get; init; }
    public int?    MakeupID              { get; init; }
    public int     SkinID                { get; init; }
    public int     BackgroundID          { get; init; }
    public int     LightID               { get; init; }
    public double  HeadRotation1         { get; init; }
    public double  HeadRotation2         { get; init; }
    public double  HeadRotation3         { get; init; }
    public double  EyeRotation1          { get; init; }
    public double  EyeRotation2          { get; init; }
    public double  EyeRotation3          { get; init; }
    public double  CamPos1               { get; init; }
    public double  CamPos2               { get; init; }
    public double  CamPos3               { get; init; }
    public double? Morph1E               { get; init; }
    public double? Morph1N               { get; init; }
    public double? Morph1S               { get; init; }
    public double? Morph1W               { get; init; }
    public double? Morph2E               { get; init; }
    public double? Morph2N               { get; init; }
    public double? Morph2S               { get; init; }
    public double? Morph2W               { get; init; }
    public double? Morph3E               { get; init; }
    public double? Morph3N               { get; init; }
    public double? Morph3S               { get; init; }
    public double? Morph3W               { get; init; }
    public double? Morph4E               { get; init; }
    public double? Morph4N               { get; init; }
    public double? Morph4S               { get; init; }
    public double? Morph4W               { get; init; }
    public int     StationID             { get; init; }
    public int     SolarSystemID         { get; init; }
    public int     ConstellationID       { get; init; }
    public int     RegionID              { get; init; }
    public int     FreeReSpecs           { get; set; }
    public long    NextReSpecTime        { get; set; }
    public long    TimeLastJump          { get; set; }
    public int     TitleMask             { get; set; }
    public int?    WarFactionID          { get; set; }
    public int     CorpAccountKey        { get; set; }
    public long    GrantableRoles        { get; set; }
    public long    GrantableRolesAtHQ    { get; set; }
    public long    GrantableRolesAtBase  { get; set; }
    public long    GrantableRolesAtOther { get; set; }
    public int?    BaseID                { get; set; }
    public Item    Information           { get; init; }
}