DROP TABLE IF EXISTS `chrMedals`;

CREATE TABLE `chrMedals` (
	`medalID` INT(10) UNSIGNED NOT NULL,
	`ownerID` INT(10) UNSIGNED NOT NULL,
	`issuerID` INT(10) UNSIGNED NOT NULL,
	`date` BIGINT(20) NOT NULL,
	`reason` INT(11) NOT NULL,
	`status` INT(11) NOT NULL,
	PRIMARY KEY (`medalID`, `ownerID`) USING BTREE,
	INDEX `ownerID` (`ownerID`) USING BTREE,
	INDEX `issuerID` (`issuerID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;