DROP TABLE IF EXISTS `chrBounties`;

CREATE TABLE `chrBounties` (
	`bountyID` INT(11) NOT NULL AUTO_INCREMENT,
	`characterID` INT(10) UNSIGNED NOT NULL,
	`ownerID` INT(10) UNSIGNED NOT NULL,
	`bounty` DOUBLE(22,0) NOT NULL,
	PRIMARY KEY (`bountyID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
