DROP TABLE IF EXISTS `crpRoles`;

CREATE TABLE IF NOT EXISTS `crproles` (
  `roleID` bigint(20) unsigned NOT NULL,
  `roleName` varchar(50) DEFAULT NULL,
  `description` varchar(255) DEFAULT '',
  `shortDescription` varchar(255) DEFAULT '',
  PRIMARY KEY (`roleID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `crproles` (`roleID`, `roleName`, `description`, `shortDescription`) VALUES
(1, 'corpRoleDirector', 'Can do anything like a CEO. Can assign any role.', 'Director'),
(128, 'corpRolePersonnelManager', 'Can accept applications to join the corporation.', 'Personnel Manager'),
(256, 'corpRoleAccountant', 'Can view/use corporation accountancy info.', 'Accountant'),
(512, 'corpRoleSecurityOfficer', 'Can view the content of others hangars', 'Security Officer'),
(1024, 'corpRoleFactoryManager', 'Can perform factory management tasks.', 'Factory Manager'),
(2048, 'corpRoleStationManager', 'Can perform station management for a corporation.', 'Station Manager'),
(4096, 'corpRoleAuditor', 'Can perform audits on corporation security event logs.', 'Auditor'),
(8192, 'corpRoleHangarCanTake1', 'Can take items from this divisions hangar', 'Hangar Take [1]'),
(16384, 'corpRoleHangarCanTake2', 'Can take items from this divisions hangar', 'Hangar Take [2]'),
(32768, 'corpRoleHangarCanTake3', 'Can take items from this divisions hangar', 'Hangar Take [3]'),
(65536, 'corpRoleHangarCanTake4', 'Can take items from this divisions hangar', 'Hangar Take [4]'),
(131072, 'corpRoleHangarCanTake5', 'Can take items from this divisions hangar', 'Hangar Take [5]'),
(262144, 'corpRoleHangarCanTake6', 'Can take items from this divisions hangar', 'Hangar Take [6]'),
(524288, 'corpRoleHangarCanTake7', 'Can take items from this divisions hangar', 'Hangar Take [7]'),
(1048576, 'corpRoleHangarCanQuery1', 'Can query the content of this divisions hangar', 'Hangar Query [1]'),
(2097152, 'corpRoleHangarCanQuery2', 'Can query the content of this divisions hangar', 'Hangar Query [2]'),
(4194304, 'corpRoleHangarCanQuery3', 'Can query the content of this divisions hangar', 'Hangar Query [3]'),
(8388608, 'corpRoleHangarCanQuery4', 'Can query the content of this divisions hangar', 'Hangar Query [4]'),
(16777216, 'corpRoleHangarCanQuery5', 'Can query the content of this divisions hangar', 'Hangar Query [5]'),
(33554432, 'corpRoleHangarCanQuery6', 'Can query the content of this divisions hangar', 'Hangar Query [6]'),
(67108864, 'corpRoleHangarCanQuery7', 'Can query the content of this divisions hangar', 'Hangar Query [7]'),
(134217728, 'corpRoleAccountCanTake1', 'Can take funds from this divisions account', 'Account Take [1]'),
(268435456, 'corpRoleAccountCanTake2', 'Can take funds from this divisions account', 'Account Take [2]'),
(536870912, 'corpRoleAccountCanTake3', 'Can take funds from this divisions account', 'Account Take [3]'),
(1073741824, 'corpRoleAccountCanTake4', 'Can take funds from this divisions account', 'Account Take [4]'),
(2147483648, 'corpRoleAccountCanTake5', 'Can take funds from this divisions account', 'Account Take [5]'),
(4294967296, 'corpRoleAccountCanTake6', 'Can take funds from this divisions account', 'Account Take [6]'),
(8589934592, 'corpRoleAccountCanTake7', 'Can take funds from this divisions account', 'Account Take [7]'),
(17179869184, 'corpRoleAccountCanQuery1', 'Can query funds from this divisions account', 'Account Query [1]'),
(34359738368, 'corpRoleAccountCanQuery2', 'Can query funds from this divisions account', 'Account Query [2]'),
(68719476736, 'corpRoleAccountCanQuery3', 'Can query funds from this divisions account', 'Account Query [3]'),
(137438953472, 'corpRoleAccountCanQuery4', 'Can query funds from this divisions account', 'Account Query [4]'),
(274877906944, 'corpRoleAccountCanQuery5', 'Can query funds from this divisions account', 'Account Query [5]'),
(549755813888, 'corpRoleAccountCanQuery6', 'Can query funds from this divisions account', 'Account Query [6]'),
(1099511627776, 'corpRoleAccountCanQuery7', 'Can query funds from this divisions account', 'Account Query [7]'),
(2199023255552, 'corpRoleEquipmentConfig', 'Can deploy and configure equipment in space.', ''),
(4398046511104, 'corpRoleContainerCanTake1', 'Can take containers from this divisional hangar', 'Container Take [1]'),
(8796093022208, 'corpRoleContainerCanTake2', 'Can take containers from this divisional hangar', 'Container Take [2]'),
(17592186044416, 'corpRoleContainerCanTake3', 'Can take containers from this divisional hangar', 'Container Take [3]'),
(35184372088832, 'corpRoleContainerCanTake4', 'Can take containers from this divisional hangar', 'Container Take [4]'),
(70368744177664, 'corpRoleContainerCanTake5', 'Can take containers from this divisional hangar', 'Container Take [5]'),
(140737488355328, 'corpRoleContainerCanTake6', 'Can take containers from this divisional hangar', 'Container Take [6]'),
(281474976710656, 'corpRoleContainerCanTake7', 'Can take containers from this divisional hangar', 'Container Take [7]'),
(562949953421312, 'corpRoleCanRentOffice', 'When assigned to a member, the member can rent offices on behalf of the corporation', 'Rent Office'),
(1125899906842624, 'corpRoleCanRentFactorySlot', 'When assigned to a member, the member can rent factory slots on behalf of the corporation', 'Rent Factory Facility'),
(2251799813685248, 'corpRoleCanRentResearchSlot', 'When assigned to a member, the member can rent research facilities on behalf of the corporation', 'Rent Research Facility'),
(4503599627370496, 'corpRoleJuniorAccountant', 'Can view corporation accountancy info.', 'Junior Accountant'),
(9007199254740992, 'corpRoleStarbaseConfig', 'Can deploy and configure starbase structures in space.', 'Config Starbase Equipment'),
(18014398509481984, 'corpRoleTrader', 'Can buy and sell things for the corporation', 'Trader'),
(36028797018963968, 'corpRoleChatManager', 'Can moderate corporation/alliance communications channels.', 'Communications Officer'),
(72057594037927936, 'corpRoleContractManager', 'Can create, edit and oversee all contracts made on behalf of the corporation as well as accept contracts on behalf of the corporation', 'Contract Manager'),
(144115188075855872, 'corpRoleInfrastructureTacticalOfficer', 'Can operate defensive starbase structures', 'Starbase Defensive Operator'),
(288230376151711744, 'corpRoleStarbaseCaretaker', 'Can refuel starbases and take from silo bins.', 'Starbase Fuel Technician'),
(576460752303423488, 'corpRoleFittingManager', 'Can add and delete fittings.', 'Fitting Manager');
