CREATE TABLE `chrBookmarks` (
	`bookmarkID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`ownerID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`itemID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`typeID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`memo` VARCHAR(85) NOT NULL DEFAULT '',
	`comment` TEXT NOT NULL DEFAULT '0',
	`created` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	`x` DOUBLE NOT NULL DEFAULT '0',
	`y` DOUBLE NOT NULL DEFAULT '0',
	`z` DOUBLE NOT NULL DEFAULT '0',
	`locationID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`bookmarkID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;