DROP TABLE IF EXISTS `conContracts`;

CREATE TABLE `contracts` (
  `contractID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `issuerID` int(10) unsigned NOT NULL DEFAULT '0',
  `issuerCorpID` int(10) unsigned NOT NULL,
  `type` int(10) NOT NULL,
  `avail` int(10) NOT NULL,
  `assigneeID` int(10) NOT NULL,
  `expiretime` int(10) NOT NULL,
  `duration` int(10) NOT NULL,
  `startStationID` int(10) unsigned NOT NULL,
  `endStationID` int(10) unsigned NOT NULL,
  `price` double NOT NULL,
  `reward` double NOT NULL,
  `collateral` double NOT NULL,
  `title` varchar(85) DEFAULT NULL,
  `description` text,
  `forCorp` tinyint(1) NOT NULL,
  `status` int(10) NOT NULL,
  `isAccepted` tinyint(1) NOT NULL,
  `acceptorID` int(10) DEFAULT NULL,
  `dateIssued` bigint(20) DEFAULT NULL,
  `dateExpired` bigint(20) DEFAULT NULL,
  `dateAccepted` bigint(20) DEFAULT NULL,
  `dateCompleted` bigint(20) DEFAULT NULL,
  `volume` double DEFAULT NULL,
  `requiresAttentionByOwner` tinyint(1) NOT NULL DEFAULT '0',
  `requiresAttentionByAssignee` tinyint(1) NOT NULL DEFAULT '0',
  `crateID` int(10) unsigned NOT NULL DEFAULT '0',
  `issuerWalletKey` int(10) unsigned NOT NULL DEFAULT '0',
  `issuerAllianceID` int(10) unsigned NOT NULL DEFAULT '0',
  `acceptorWalletKey` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`contractID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
