/*Table structure for table `mktRefTypes` */

DROP TABLE IF EXISTS `mktRefTypes`;

CREATE TABLE `mktRefTypes` (
  `refTypeID` int(10) unsigned NOT NULL default '0',
  `refTypeText` varchar(100) NOT NULL default '',
  `description` mediumtext NOT NULL,
  PRIMARY KEY  (`refTypeID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `mktRefTypes` */

insert  into `mktRefTypes`(`refTypeID`,`refTypeText`,`description`) VALUES
	(0,'Undefined',''),
	(1,'Player Trading',''),
	(2,'Market Transaction',''),
	(3,'GM Cash Transfer',''),
	(4,'ATM Withdraw',''),
	(5,'ATM Deposit',''),
	(6,'Backward Compatible',''),
	(7,'Mission Reward',''),
	(8,'Clone Activation',''),
	(9,'Inheritance',''),
	(10,'Player Donation','Player gave cash to another owner'),
	(11,'Corporation Payment','CEO or Accountant transferred cash  from corp. account'),
	(12,'Docking Fee',''),
	(13,'Office Rental Fee',''),
	(14,'Factory Slot Rental Fee',''),
	(15,'Repair Bill',''),
	(16,'Bounty','Player gave cash to someone\'s  bounty pool'),
	(17,'Bounty Prize','Player got bounty prize for killing someone'),
	(18,'Agents_temporary','TEMP'),
	(19,'Insurance',''),
	(20,'Mission Expiration',''),
	(21,'Mission Completion',''),
	(22,'Shares',''),
	(23,'Courier Mission Escrow',''),
	(24,'Mission Cost',''),
	(25,'Agent Miscellaneous','Agent paid you'),
	(26,'Miscellaneous Payment To Agent','You paid agent'),
	(27,'Agent Location Services','You paid agent to locate somebody'),
	(28,'Agent Donation','You donated/bribed the agent'),
	(29,'Agent Security Services','You paid agent to clean your rep'),
	(30,'Agent Mission Collateral Paid','You gave agent collateral for a mission'),
	(31,'Agent Mission Collateral Refunded','The agent returned collateral to you'),
	(32,'Agents_preward','The agent gave you this when you accepted the mission'),
	(33,'Agent Mission Reward','The agent gave you this as a reward'),
	(34,'Agent Mission Time Bonus Reward','The agent gave you this as a special reward for fast mission completion'),
	(35,'CSPA','CONCORD Spam Prevention Act'),
	(36,'CSPAOfflineRefund','Refunded CSPA charge because the other party was not online'),
	(37,'Corporation Account Withdrawal','Withdrawal from corporation account'),
	(38,'Corporation Dividend Payment',''),
	(39,'Corporation Registration Fee',''),
	(40,'Corporation Logo Change Cost',''),
	(41,'Release Of Impounded Property','Charge for the receipt of goods from a corporation hangar that is no longer rented'),
	(42,'Market Escrow',''),
	(43,'Agent Services Rendered','For miscellaneous services rendered by the agent'),
	(44,'Market Fine Paid',''),
	(45,'Corporation Liquidation','Funds from the liquidation of a corporation to a shareholder'),
	(46,'Broker fee',''),
	(47,'Corporation Bulk Payment','A payment from a corporation'),
	(48,'Alliance Registration Fee',''),
	(49,'War Fee',''),
	(50,'Alliance Maintainance Fee',''),
	(51,'Contraband Fine',''),
	(52,'Clone Transfer',''),
	(53,'Acceleration Gate Fee',''),
	(54,'Transaction Tax','Sales tax paid to the SCC for any transaction'),
	(55,'Jump Clone Installation Fee',''),
	(56,'Manufacturing','Installation and runtime cost for a manufacturing job'),
	(57,'Researching Technology','Installation and runtime cost for a technological research job'),
	(58,'Researching Time Productivity','Installation and runtime cost for a time productivity research job'),
	(59,'Researching Material Productivity','Installation and runtime cost for a material productivity research job'),
	(60,'Copying','Installation and runtime cost for a blueprint copying job'),
	(61,'Duplicating','Installation and runtime cost for an item duplication job'),
	(62,'Reverse Engineering','Installation and runtime cost for a reverse engineering job');
	(63, 'Contract Auction Bid', ''),
	(64, 'Contract Auction Bid Refund', ''),
	(65, 'Contract Collateral', ''),
	(66, 'Contract Reward Refund', ''),
	(67, 'Contract Auction Sold', ''),
	(68, 'Contract Reward', ''),
	(69, 'Contract Collateral Refund', ''),
	(70, 'Contract Collateral Payout', ''),
	(71, 'Contract Price', ''),
	(72, 'Contract Brokers Fee', ''),
	(73, 'Contract Sales Tax', ''),
	(74, 'Contract Deposit', ''),
	(75, 'Contract Deposit Sales Tax', ''),
	(76, 'EVE Time Code Exchange', ''),
	(77, 'Contract Auction Bid (corp)', ''),
	(78, 'Contract Collateral Deposited (corp)', ''),
	(79, 'Contract Price Payment (corp)', ''),
	(80, 'Contract Brokers Fee (corp)', ''),
	(81, 'Contract Deposit (corp)', ''),
	(82, 'Contract Deposit Refund', ''),
	(83, 'Contract Reward Deposited', ''),
	(84, 'Contract Reward Deposited (corp)', ''),
	(85, 'Bounty Prizes', ''),
	(86, 'Advertisement Listing Fee', ''),
	(87, 'Medal Creation', ''),
	(88, 'Medal Issued', ''),
	(90, 'DNA Modification Fee', ''),
	(91, 'Sovereignty bill', '');